version: '2'
services:
  mongodb:
    container_name: mstar-mongodb
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "/home/sunday/workspace/docker/data/mongodb/data:/data/db"


