version: '2'
services:
  ftp-server:
    image: stilliard/pure-ftpd:hardened
    environment:
      - FTP_USER_NAME=mstar
      - FTP_USER_PASS=123456
      - FTP_USER_HOME=/home/mstar
      - PUBLICHOST=localhost
    ports:
      - "50021:21"
      - "30000-30009:30000-30009"
    volumes:
      - /home/sunday/workspace/docker/data/cdn:/home/mstar

    #  ftpd_server:
    #    image: stilliard/pure-ftpd:hardened
    #    container_name: pure-ftpd
    #    ports:
    #      - "21:21"
    #      - "30000-30009:30000-30009"
    #    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
    #      - "/home/sunday/ftp/data:/home/sunday/"
    #    environment:
    #      PUBLICHOST: "localhost"
    #      FTP_USER_NAME: sunday
    #      FTP_USER_PASS: 123456
    #      FTP_USER_HOME: /home/sunday
    #    restart: always

  web-server:
    image: nginx
    volumes_from:
      - ftp-server
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - "50080:80"


