version: '2'

services:
  mysql57:
    image: mysql:5.7
    container_name: mysql-kite
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_USER=sunday
    - MYSQL_PASSWORD=123456
    - MYSQL_DATABASE=kite
    hostname: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - /home/sunday/workspace/docker/data/mysql/kite/conf.d:/etc/mysql/conf.d:ro
    - /home/sunday/workspace/docker/data/mysql/kite/data:/var/lib/mysql:Z
    - /home/sunday/workspace/docker/data/mysql/kite/log:/var/log/mysql:Z
    ports:
    - 8306:3306

