version: '2'

services:

  redmine:
    image: redmine
    ports:
    - 127.0.0.1:3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: 123456
    volumes:
    - /home/sunday/workspace/docker/data/redmine/redmine/data:/usr/src/redmine/files
    depends_on:
    - db
    restart: always

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: redmine
    volumes:
    - /home/sunday/workspace/docker/data/redmine/mariadb/data:/var/lib/mysql:Z
    - /home/sunday/workspace/docker/data/redmine/mariadb/conf.d:/etc/mysql/conf.d:ro
    restart: always
