version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: jenkins
    volumes:
      - /home/sunday/workspace/docker/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "10180:8080"
      - "10100:50000"
