version: '2'
services:
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /home/sunday/workspace/docker/data/nginx:/var/www/html
    ports:
      - "8080:80"
# environment:
# - NGINX_HOST=foobar.com
# - NGINX_PORT=80

