version: '2'
services:
  mongodb:
    container_name: mongodb-4.0
    image: mongo:4.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "/home/sunday/workspace/docker/data/mongodb4.0/data:/data/db"

