version: '3'
services:
  ftp-server:
    image: stilliard/pure-ftpd:hardened
    environment:
      - FTP_USER_NAME=bob
      - FTP_USER_PASS=12345
      - FTP_USER_HOME=/home/bob
      - PUBLICHOST=192.168.1.37
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
