version: '2'
services:
  mysql:
    image: mysql:latest
    volumes:
    - /home/sunday/workspace/docker/data/gogs/mysql:/var/lib/mysql:Z
    environment:
    - MYSQL_DATABASE=gogs
    - MYSQL_USER=gogs
    - MYSQL_PASSWORD=LCmW43PPhlJK
    - MYSQL_ROOT_PASSWORD=9mxlT2zjP4xS
    command: --collation-server=utf8mb4_unicode_ci --character-set-server=utf8mb4

  gogs:
    image: gogs/gogs
    container_name: gogs
    depends_on:
      - mysql 
    volumes:
      - /home/sunday/workspace/docker/data/gogs/gogs:/data
    ports:
      - "10222:22"
      - "10280:3000"
